#theme: jekyll-theme-minimal

remote_theme: daattali/beautiful-jekyll

# Custom section
custom_section:
  title: "🚀 Host Your Resume!"
  description: "Please see my [ReadMe file](link-to-your-readme) on how to host your resume on GitHub Pages."
